services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - rustfs_data:/data

#  api:
#    build: .
#    restart: unless-stopped
#    ports:
#      - '3000:3000'
#    environment:
#      MONGODB_URI: ${MONGODB_URI_DOCKER}
#    depends_on:
#      - mongo

volumes:
  mongo_data:
  rustfs_data:
